baseURL = 'https://quangkhaidam93.github.io/my-blogs/'
languageCode = 'en-us'
title = 'DQK Dev Blog'
theme = "hugo-blog-awesome"

defaultContentLanguage = "en-us"

[[params.socialIcons]]
name = "github"
url = "https://github.com/quangkhaidam93"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/kdq/"

[[params.socialIcons]]
name = "stackoverflow"
url = "https://stackoverflow.com/users/10398593/quang-kh%e1%ba%a3i-%c4%90%c3%a0m"


############################## English language ################################
[Languages.en-us]
languageName = "English"
languageCode = "en-us"
contentDir = "content/en"
weight = 1

[Languages.en-us.menu]
[[Languages.en-us.menu.main]]
# The page reference (pageRef) is useful for menu highlighting
# When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
pageRef = "/"
name = 'Home'
url = '/'
weight = 10
[[Languages.en-us.menu.main]]
pageRef = "posts"
name = 'Posts'
url = '/posts/'
weight = 20

# [Languages.en-us.params]
# sitename = "Awesome hugo blog"
# defaultColor = "auto"
# description = "Minimal Hugo blog theme with light and dark mode support"
# mainSections = ['posts']
# toc = true                                                               # set to false to disable table of contents 'globally'
# tocOpen = false                                                          # set to true to open table of contents by default
# goToTop = true                                                           # set to false to disable 'go to top' button
# additionalScripts = ['js/custom.js', 'js/custom-2.js']
# # Will try to load 'assets/js/custom.js' and 'assets/js/custom-2.js'.
# # Your custom scripts will be concatenated to one file `custom.js`.
# # When building for production it will be minified.
# # The file `custom.js` is loaded on each page (before body tag ends).
# dateFormat = "" # date format used to show dates on various pages. If nothing is specified, then "2 Jan 2006" format is used.
# # See https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference for available date formats.
# rssFeedDescription = "summary" # available options: 1) summary 2) full
# # summary - includes a short summary of the blog post in the RSS feed. Generated using Hugo .Summary .
# # full - includes full blog post in the RSS feed. Generated using Hugo .Content .
# # By default (or if nothing is specified), summary is used.

[Languages.en-us.params.author]
avatar = "avatar.jpg" # put the file in assets folder; also ensure that image has same height and width
# Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
intro = "My funcking life as a Software Engineer"
name = "Quang Khải Đàm"
description = "Lemmi tell you a story about coder life"

# # Allow to override webmanifest options
[Languages.en-us.params.webmanifest]
name = "sitename"         # will use "params.sitename" or "title" by default
short_name = "sitename"   # same as name
start_url = "/"           # will use homepage url by default
theme_color = "#434648"   # default is "#434648" (base color of text). Also will override html `<meta name="theme-color" />`
background_color = "#fff" # by default depend on "params.defaultColor" for "light" or "auto" will be set to "#fff" for dark will be "#131418" (color of dark mode background)
display = "standalone"

############################## Vietnamese language ################################
[Languages.vi-vn]
languageName = "Việt Nam"
languageCode = "vi-vn"
contentDir = "content/vi"
weight = 1

[Languages.vi-vn.menu]
[[Languages.vi-vn.menu.main]]
# The page reference (pageRef) is useful for menu highlighting
# When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
pageRef = "/"
name = 'Trang chủ'
url = '/'
weight = 10
[[Languages.vi-vn.menu.main]]
pageRef = "posts"
name = 'Bài viết'
url = '/posts/'
weight = 20

# [Languages.en-us.params]
# sitename = "Awesome hugo blog"
# defaultColor = "auto"
# description = "Minimal Hugo blog theme with light and dark mode support"
# mainSections = ['posts']
# toc = true                                                               # set to false to disable table of contents 'globally'
# tocOpen = false                                                          # set to true to open table of contents by default
# goToTop = true                                                           # set to false to disable 'go to top' button
# additionalScripts = ['js/custom.js', 'js/custom-2.js']
# # Will try to load 'assets/js/custom.js' and 'assets/js/custom-2.js'.
# # Your custom scripts will be concatenated to one file `custom.js`.
# # When building for production it will be minified.
# # The file `custom.js` is loaded on each page (before body tag ends).
# dateFormat = "" # date format used to show dates on various pages. If nothing is specified, then "2 Jan 2006" format is used.
# # See https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference for available date formats.
# rssFeedDescription = "summary" # available options: 1) summary 2) full
# # summary - includes a short summary of the blog post in the RSS feed. Generated using Hugo .Summary .
# # full - includes full blog post in the RSS feed. Generated using Hugo .Content .
# # By default (or if nothing is specified), summary is used.

[Languages.vi-vn.params.author]
avatar = "avatar.jpg" # put the file in assets folder; also ensure that image has same height and width
# Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
intro = "Cuộc sống đầy drama của một lập trình viên"
name = "Quang Khải Đàm"
description = "Để tui kể cho bạn nghe ..."

# # Allow to override webmanifest options
[Languages.vi-vn.params.webmanifest]
name = "sitename"         # will use "params.sitename" or "title" by default
short_name = "sitename"   # same as name
start_url = "/"           # will use homepage url by default
theme_color = "#434648"   # default is "#434648" (base color of text). Also will override html `<meta name="theme-color" />`
background_color = "#fff" # by default depend on "params.defaultColor" for "light" or "auto" will be set to "#fff" for dark will be "#131418" (color of dark mode background)
display = "standalone"
