baseURL = 'https://quangkhaidam93.github.io/my-blogs/'
languageCode = 'en-us'
title = 'DQK Dev Blog'
theme = "hugo-blog-awesome"

defaultContentLanguage = "vi-vn"

[[params.socialIcons]]
name = "github"
url = "https://github.com/quangkhaidam93"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/kdq/"

[[params.socialIcons]]
name = "stackoverflow"
url = "https://stackoverflow.com/users/10398593/quang-kh%e1%ba%a3i-%c4%90%c3%a0m"


############################## English language ################################
[Languages.en-us]
languageName = "English"
languageCode = "en-us"
contentDir = "content/en"
weight = 1

[Languages.en-us.menu]
[[Languages.en-us.menu.main]]
# The page reference (pageRef) is useful for menu highlighting
# When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
pageRef = "/"
name = 'Home'
url = '/'
weight = 10
[[Languages.en-us.menu.main]]
pageRef = "posts"
name = 'Posts'
url = '/posts/'
weight = 20

# [Languages.en-us.params]
# sitename = "Awesome hugo blog"
# defaultColor = "auto"
# description = "Minimal Hugo blog theme with light and dark mode support"
# mainSections = ['posts']
# toc = true                                                               # set to false to disable table of contents 'globally'
# tocOpen = false                                                          # set to true to open table of contents by default
# goToTop = true                                                           # set to false to disable 'go to top' button
# additionalScripts = ['js/custom.js', 'js/custom-2.js']
# # Will try to load 'assets/js/custom.js' and 'assets/js/custom-2.js'.
# # Your custom scripts will be concatenated to one file `custom.js`.
# # When building for production it will be minified.
# # The file `custom.js` is loaded on each page (before body tag ends).
# dateFormat = "" # date format used to show dates on various pages. If nothing is specified, then "2 Jan 2006" format is used.
# # See https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference for available date formats.
# rssFeedDescription = "summary" # available options: 1) summary 2) full
# # summary - includes a short summary of the blog post in the RSS feed. Generated using Hugo .Summary .
# # full - includes full blog post in the RSS feed. Generated using Hugo .Content .
# # By default (or if nothing is specified), summary is used.

[Languages.en-us.params.author]
avatar = "avatar.jpg" # put the file in assets folder; also ensure that image has same height and width
# Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
intro = "My fucking life as a Software Engineer"
name = "Quang Khải Đàm"
description = "Lemmi tell you a story ..."

# # Allow to override webmanifest options
[Languages.en-us.params.webmanifest]
name = "sitename"         # will use "params.sitename" or "title" by default
short_name = "sitename"   # same as name
start_url = "/"           # will use homepage url by default
theme_color = "#434648"   # default is "#434648" (base color of text). Also will override html `<meta name="theme-color" />`
background_color = "#fff" # by default depend on "params.defaultColor" for "light" or "auto" will be set to "#fff" for dark will be "#131418" (color of dark mode background)
display = "standalone"

############################## Vietnamese language ################################
[Languages.vi-vn]
languageName = "Việt Nam"
languageCode = "vi-vn"
contentDir = "content/vi"
weight = 1

[Languages.vi-vn.menu]
[[Languages.vi-vn.menu.main]]
# The page reference (pageRef) is useful for menu highlighting
# When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
pageRef = "/"
name = 'Trang chủ'
url = '/'
weight = 10
[[Languages.vi-vn.menu.main]]
pageRef = "posts"
name = 'Bài viết'
url = '/posts/'
weight = 20

# [Languages.en-us.params]
# sitename = "Awesome hugo blog"
# defaultColor = "auto"
# description = "Minimal Hugo blog theme with light and dark mode support"
# mainSections = ['posts']
# toc = true                                                               # set to false to disable table of contents 'globally'
# tocOpen = false                                                          # set to true to open table of contents by default
# goToTop = true                                                           # set to false to disable 'go to top' button
# additionalScripts = ['js/custom.js', 'js/custom-2.js']
# # Will try to load 'assets/js/custom.js' and 'assets/js/custom-2.js'.
# # Your custom scripts will be concatenated to one file `custom.js`.
# # When building for production it will be minified.
# # The file `custom.js` is loaded on each page (before body tag ends).
# dateFormat = "" # date format used to show dates on various pages. If nothing is specified, then "2 Jan 2006" format is used.
# # See https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference for available date formats.
# rssFeedDescription = "summary" # available options: 1) summary 2) full
# # summary - includes a short summary of the blog post in the RSS feed. Generated using Hugo .Summary .
# # full - includes full blog post in the RSS feed. Generated using Hugo .Content .
# # By default (or if nothing is specified), summary is used.

[Languages.vi-vn.params.author]
avatar = "avatar.jpg" # put the file in assets folder; also ensure that image has same height and width
# Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
intro = "Nơi lưu trữ những suy nghĩ, kiến thức và trải nghiệm cá nhân của mình"
name = "Quang Khải Đàm"
description = "Vì hạn chế tiếng Anh (cảm thấy không tự tin lắm) và muốn chia sẻ một cách cảm xúc nhất nên mình sẽ sử dụng tiếng Việt và ngôn ngữ của mình để chia sẻ các chủ đề xung quanh cuộc sống của mình. Mục đích của blog này là để mình ở tương lai có tư liệu tham khảo lại mình của quá khứ, để xem mình đã đi được bao lâu và bao xa trên hành trình của bản thân. Blog này không chỉ bao gồm suy nghĩ mà còn về các kiến thức xung quanh các chủ đề như Toán học, Lập trình, Nghiên cứu AI, Sách, ... Hy vọng có thể giúp ích cho bất kì ai trên thế giới này.\n Note: Mình sẽ cố gắng cải thiện khả năng viết tiếng Anh nhưng chưa phải là năm nay (2025)."

# # Allow to override webmanifest options
[Languages.vi-vn.params.webmanifest]
name = "sitename"         # will use "params.sitename" or "title" by default
short_name = "sitename"   # same as name
start_url = "/"           # will use homepage url by default
theme_color = "#434648"   # default is "#434648" (base color of text). Also will override html `<meta name="theme-color" />`
background_color = "#fff" # by default depend on "params.defaultColor" for "light" or "auto" will be set to "#fff" for dark will be "#131418" (color of dark mode background)
display = "standalone"
